sudo: required
language: generic
services:
- docker
before_install:
- docker build -t ethcore:parity-arm .
- docker run -d --name parity-arm ethcore:parity-arm
script:
- docker start parity-arm
- docker ps
- docker cp parity-arm:/build/parity/target/arm-unknown-linux-gnueabihf/release/parity
  parity-arm
- docker stop parity-arm
- docker rm parity-arm
- tar czf parity-arm-${TRAVIS_TAG}.tar.gz *
deploy:
  provider: releases
  api_key:
    secure: t+oGT/4lsy7IScw5s86Dpntl5Nyck4qG6nhHwMScc6FYzwLldgwgJaafL8Ej+HG+b7nFLriN+Snoa4YQ5o74X5ZlSWubVREOYQlL/fq7vcPB0DwAZ0Jufq1QW2R1M+3SwwF1eAwTv2W3G7A2K7dxjCVvENcy/gdxnZ36NeUPsqaCC9UcI2Yc7+4jyQwvx6ZfBvQeu+HbKENA0eUNs2ZQOID/1IPy0LJBvSyxAQYsysXdjTzGdNu4+Iba20E8uWYe4fAbgz+gwGarXg1L6D6gKyMlWkViqWjvXWBuDJJqMQZ3rw41AwZOoh3mKd2Lc0l6l4oZcEqPuob0yKTNjz1tuJy9xKTC2F2bDzsvUgk1IRfMK5ukXXXS09ZCZWuA9/GtnsqJ1xGTiwX+DhQzpVBHaBiseSNlYE1YN/3jNyGY+iSts1qut+1BwE7swmcTLsAPoAy8Ue+f7ErNoCg1lm71vq7VO2DLn7x2NqHyHUEuJ+7olDHSdE84G7d9otDRu/+TfMOw7GXwTaha6yJRInuNsnj4CFMLNVvYACzCC2idB7f7nUZoSFi9jf18S9fCMPVmazMrFj4g95HWrVHkjpV5zRTeUdTWw6DJl6pC9HFqORHdCvLv4Rc4dm5r3CmOcAQ0ZuiccV2oKzw4/Wic96daae8M5f5KSQ/WTr+h0wXZKp0=
  file: parity-arm-${TRAVIS_TAG}.tar.gz
  on:
    tags: true
branches:
  only:
  - master
  - "/^v\\d+\\.\\d+\\.\\d+.*$/"
notifications:
  slack:
    rooms:
    - ethcore:4EGxt9WP6AS7uX4JKXSfR9vi#chatops
